
str ="""Anhui Agricultural University,
	Anhui Medical University,
	Anhui Normal University,
	Anshan Normal University Liaoning China,
	Beihua University,
	Beijing Film Academy,
	Beijing Foreign Studies University,
	Beijing Forestry University,
	Beijing International Studies University,
	Beijing Jiaotong University,
	Beijing Language and Culture University,
	Beijing Normal University,
	Beijing Sport University,
	Beijing Technology and Business University,
	Beijing University of Chemical Technology,
	Beijing University of Chinese Medicine,
	Beijing University of Posts and Telecommunications,
	Beijing University of Technology,
	Capital Institute of Physical Education,
	Capital Medical University,
	Capital Normal University,
	Capital University of Economics & Business,
	Central Academy of Fine Arts,
	Central China Normal University,
	Central Conservatory of Music,
	Central South University,
	Central University of Finance and Ecnomics,
	Chang'an University,
	Changchun University,
	Changchun University of Chinese Medicine,
	China University of Political Science and Law,
	Changsha University of Science and Technology,
	Chengdu University of Traditional Chinese Medicine,
	China Academy of Art,
	China Agriculture University,
	China Conservatory,
	China Foreign Affairs University,
	China Medical University,
	China Pharmaceutical University,
	China Three Gorges University,
	China Univeristy of Political Science and Law,
	China University of Geosciences (Beijing),
	China University of Geosciences (Wuhan),
	China University of Mining and Technology,
	China University of Petroleum,
	China University of Petroleum (Huadong)	China Youth University of Political Studies,
	Chongqing Jiaotong University,
	Chongqing Medical University,
	Chongqing Medical University,
	Chongqing University,
	Chongqing University of Posts and Telecommunications,
	Communication University of China,
	Dalian Jiaotong University,
	Dalian Medical University,
	Dalian Polytechnic University,
	Dalian University of Foreign Languages,
	Dalian University of Technology,
	Dalian University of Technology,
	Donghua University,
	East China Normal University,
	East China University of Political Science and Law,
	East China University of Science & Technology,
	Fudan University,
	Fujian Agricultrue and Forestry University,
	Fujian Medical University,
	Fujian Normal University,
	Fujian University of Technology,
	Fuzhou University,
	Gannan Normal University,
	Guangdong University of Foreign Studies,
	Guangxi Medical University,
	Guangxi Normal University,
	Guangxi Teachers Education University,
	Guangxi University,
	Guangxi University For Nationalities,
	Guangzhou Medical University,
	Guangzhou University of Chinese Medicine,
	Guilin University of Electronic Technology,
	Guizhou Minzu University,
	Guizhou Normal University,
	Guizhou University,
	Hainan Normal University,
	Hainan University,
	Hangzhou Normal University,
	Hangzhou Normal University,
	Harbin Institute of Technology,
	Harbin Medical University,
	Harbin Normal University,
	Harbin University of Science and Technology,
	Hebei Medical University,
	Hebei Normal University,
	Hebei University,
	Hebei University of Economics and Business,
	Hebei University of Technology,
	Hefei University,
	Hefei University of Technology,
	Heihe University,
	Heilongjiang University,
	Heilongjiang University of Chinese Medicine,
	Henan University
	Henan University of Chinese Medicine,
	Henan University of Technology,
	Hohai University,
	Huangshan University,
	Huazhong Agricultural University,
	Huazhong University of Science and Technology,
	Hubei University,
	Hubei University of Chinese Medicine,
	Hunan Normal University,
	Hunan University,
	Inner Mongolia Agricultural University,
	Inner Mongolia Normal University,
	Inner Mongolia University,
	Inner Mongolia University of Technology,
	Inner Mongolia University of Technology,
	Jiangnan University,
	Jiangsu University,
	Jiangxi Agricultural University,
	Jiangxi Normal University,
	Jiangxi University of Finance and Economics,
	Jiangxi University of Traditional Chinese Medicine,
	Jilin Agricultural University,
	Jilin Normal University,
	Jilin University,
	Jingdezhen Ceramic Institute,
	Kunming Medical University,
	Kunming University of Science and Technology,
	Lanzhou Jiaotong University,
	Lanzhou University,
	Lanzhou University of Technology,
	Jiangsu University of Science and Technology,
	Beihang University,
	Chongqing Technology & Business University,
	Harbin Engineering University,
	Liaoning Medical University,
	Liaoning Normal University,
	Liaoning Shihua University,
	Liaoning Technical University,
	Liaoning University,
	Liaoning University of Technology,
	Liaoning University of Traditional Chinese Medicine,
	Ludong University,
	Minzu University of China,
	Mudanjiang Normal University,
	Nanchang Hangkong University,
	Nanchang University,
	Nanjing Agricultural University,
	East China University of Science and Technology,
	Nanjing Normal University,
	Nanjing Universit,
	Nanjing University of Aeronautics and Astronautics,
	Nanjing University of Chinese Medicine,
	Nanjing University of Information Science and Technology,
	Nanjing University of Science and Technology,
	Nanjing University of the Arts,
	Nankai University,
	Ningbo Universit,
	Ningbo University of Technology,
	Ningxia Medical University,
	Ningxia University,
	North China Electric Power Universit,
	Northeast Agricultural University,
	Northeast Dianli University,
	Northeast Forestry University,
	Northeast Normal Universit,
	Northeastern University,
	Northwest A&F University,
	Northwest Normal University,
	Northwest Normal University,
	Northwest University,
	Ocean University of China,
	Peking University,
	Qingdao University,
	Qingdao University of Science and Technology,
	Qinghai Nationalities University,
	Qinghai University
	Qiqihar University,
	Renmin University of China,
	Shaanxi Normal University,
	Shaanxi University of Chinese Medicine,
	Shandong Normal University,
	Shandong University,
	Shandong University of Science and Technology,
	Shandong University of Technology,
	Shanghai Conservatory of Musi,
	Shanghai International Studies University,
	Shanghai Jiaotong University,
	Shanghai Maritime University,
	Shanghai Normal University,
	Shanghai Ocean University,
	Shanghai University,
	Shanghai University of Finance and Economics,
	Shanghai University of International Business and Economic,
	Shanghai University of Political Science and Law,
	Shanghai University of Sport,
	Shanghai University of Traditional Chinese Medicine,
	Shantou University,
	Shanxi University,niversity,
	Shenyang Jianzhu University,
	Shenyang Ligong University,
	Shenyang Normal University,
	Shenyang University of Technology,
	Shihezi University,
	Sichuan International Studies University,
	Sichuan University,
	Soochow University,
	South China Agricultural University,
	South China Normal University,
	South China University of Technolog,
	Southeast University,
	Southern Medical University,
	Southwest Jiaotong University,
	Southwest University	Southwestern University of Finance and Economics,
	Sun Yat-Sen University,
	Taiyuan University of Technology,
	The Central Academy of Drama,
	The Graduate School of the Chinese Academy of Agricultural Sciences,
	Tianjin Foreign Studies University,
	Tianjin Medical University,
	Tianjin Polytechnic University,
	Tianjin University,
	Tianjin University of Finance and Economics,
	Tianjin University of Science and Technology,
	Tianjin University of Technology,
	Tianjin University of Technology and Education,
	Tianjin University of Traditional Chinese Medicine,
	Tianjing Normal University,
	Tongji University,
	Tsinghua University	University of Chinese Academy of Sciences,
	University of Electronic Science and Technology of China,
	University of International Business and Economics,
	University of Jinan,
	University of Science and Technology of China,
	University of Science and Technology Beijing,
	University of Science and Technology Liaoning,
	University of Shanghai for Science and Technology,
	Wenzhou Medical University,
	Wenzhou University,
	Wuhan Institute of Physical Education,
	Wuhan Textile University,
	Wuhan University,
	Wuhan University of Technology,
	Wuyi University,
	Xiamen University,
	Xiamen University of Technology,
	Xian International Studies University,
	Xi'an Shiyou University,
	Xi'an Jiaotong University
	Xidian University,
	Xiangtan University
	Xinjiang Normal University,
	Xinjiang Medicine University
	Xinjiang University
	Yanbian University,
	Yangtze University,
	Yangzhou University,
	Yanshan University,
	Yantai University,
	Yunnan Agricultural University,
	Yunnan Normal University,
	Yunnan University,
	Yunnan University of Finance and Economics,
	Yunnan University of Nationalities,
	Zhejiang Gongshang University,
	Zhejiang Normal University,
	Zhejiang Ocean University,
	Zhejiang Sci-Tech University,
	Zhejiang University,
	Zhejiang University of Science & Technology,
	Zhejiang University of Technology,
	Zhengzhou University,
	Zhongnan University of Economics and Law,
	Schwarzman Scholars,
	Western International School of Shanghai
	"""
str_data = """Harbin Institute of Technology,
Central South University,
The University of Science and Technology of China,
Renmin University of China,
Fudan University,
Tsinghua University,
Xidian University,
xiamen,
Hunan University,
Nankai University,
Southwest Jiaotong University,
Chongqing University,
East China University of Science and Technology,
Donghua University,
wuhan university,
Beihang University,
Zhejiang University,
Peking University

"""
universities_list = str.split(",")
Univeristy_offering_data = str_data.split(",")
university = input("University Name: ")
if university in str:
    print(True)
    Univeristy_offering_data.append(university)

print(Univeristy_offering_data)       
    
# else: 
#     print("university not included")

# print(for_data_science)

